package com.lst.lstjx.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_INFOS.
 */
public class GroupInfos {

    private Long id;
    private String groupid;
    private String groupname;
    private String status;
    private String portrait;

    public GroupInfos() {
    }

    public GroupInfos(Long id) {
        this.id = id;
    }

    public GroupInfos(Long id, String groupid, String groupname,String portrait,  String status) {
        this.id = id;
        this.groupid = groupid;
        this.groupname = groupname;
        this.status = status;
        this.portrait = portrait;
    }

    public String getPortrait() {
		return portrait;
	}

	public void setPortrait(String portrait) {
		this.portrait = portrait;
	}

	public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    public String getGroupid() {
		return groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	public String getGroupname() {
		return groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
